version: 2
updates:
- package-ecosystem: pip
  directory: "/{{cookiecutter.project_name}}/src/requirements"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 1
  versioning-strategy: "increase-if-necessary"
  target-branch: develop
