# Generated by Django 2.0.8 on 2018-11-16 07:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("wagtailcore", "0040_page_draft_title")]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gtm_id", models.CharField(blank=True, max_length=50)),
                (
                    "google_site_verification",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "cookie_content",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="Cookie bar content"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site setting",
                "verbose_name_plural": "Site settings",
            },
        )
    ]
