# Generated by Django 2.0.8 on 2018-10-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("customimage", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="file_hash",
            field=models.CharField(blank=True, editable=False, max_length=40),
        )
    ]
