# Generated by Django 2.0.8 on 2018-10-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("customdocument", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="customdocument",
            name="file_size",
            field=models.PositiveIntegerField(editable=False, null=True),
        )
    ]
