[project]
name = "company_project"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "Django==6.0.6",
    "gunicorn==26.0.0",
    "gevent==26.5.0",
    "psycopg==3.3.4",
    "python-dotenv==1.2.2",
    "sentry_sdk[django]==2.64.0",
    "wagtail==7.4.2",
    "wagtail-meta-preview==4.2.1",
    "wagtail_headless_preview==0.9.0",
    "whitenoise==6.12.0",
]

[dependency-groups]
test = [
    "coverage",
    "pytest~=9.1.1",
    "pytest-django==4.12.0",
    "pytest-env",
    "wagtail-factories==4.5.0",
]
dev = [
    {include-group = "test"},
    "django-debug-toolbar",
    "django-stubs==6.0.6",
    "djangorestframework-stubs==3.17.0",
    "mypy==2.1.0",
    "debugpy",
    "ruff",
]
prod = []
stage = []

[tool.uv]
package = false

[tool.ruff]
line-length = 88

exclude = [
    "venv",
    "*/migrations/*",
    "node_modules",
]

[tool.ruff.lint]
# Never enforce `E501` (line length violations).
ignore = ["E501"]
# Enable isort rules for import sorting
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"pipit/settings/dev.py" = ["F405", "F403"]
"pipit/settings/test.py" = ["F405", "F403"]
"pipit/settings/stage.py" = ["F405", "F403"]
"pipit/settings/prod.py" = ["F405", "F403"]
