# Generated by Django 2.0.8 on 2018-10-26 06:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("{{ cookiecutter.project_slug }}", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="{{ cookiecutter.project_slug }}.BasePage",
                    ),
                ),
                (
                    "author",
                    models.TextField(blank=True, null=True, verbose_name="Author"),
                ),
                (
                    "wysiwyg",
                    wagtail.core.fields.RichTextField(
                        blank=True, null=True, verbose_name="Wysiwyg"
                    ),
                ),
            ],
            options={"verbose_name": "Article"},
            bases=("{{ cookiecutter.project_slug }}.basepage",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="{{ cookiecutter.project_slug }}.BasePage",
                    ),
                )
            ],
            options={"verbose_name": "Home"},
            bases=("{{ cookiecutter.project_slug }}.basepage",),
        ),
    ]
