# docker compose override for running python with a local interpreter
services:
  web:
    depends_on: []
    environment:
      - PYTHON_HOST=http://host.docker.internal

  python:
    build:
      context: ./src
      dockerfile: Dockerfile_noop
    volumes: []
    depends_on: []

