- name: Symlink Django .env
  file:
    src: "{{ ansistrano_shared_path }}/.env"
    dest: "{{ ansistrano_release_path.stdout }}/src/.env"
    state: link

- name: Symlink Next .env
  file:
    src: "{{ ansistrano_shared_path }}/.env.next"
    dest: "{{ ansistrano_release_path.stdout }}/src/frontend/.env.local"
    state: link

- name: Symlink media
  file:
    src: "{{ ansistrano_shared_path }}/media"
    dest: "{{ ansistrano_release_path.stdout }}/src/media"
    state: link

- name: Install uv
  shell: "curl -LsSf https://astral.sh/uv/0.10.3/install.sh | sh"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/uv"

- name: Install dependencies in virtualenv
  shell: >
    cd {{ ansistrano_release_path.stdout }}/src &&
    {{ ansible_env.HOME }}/.local/bin/uv sync --frozen
  environment:
    UV_PROJECT_ENVIRONMENT: "{{ ansistrano_shared_path }}/venv"

- name: Run Migrations
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py migrate --noinput"

- name: Update wagtail search index
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py update_index"

