# vi: set ft=ruby :

# Use this when you want to try out the deploy script
Vagrant.configure("2") do |config|
    config.vm.define 'web01' do |config|
        config.vm.box = 'ubuntu/trusty64'
        config.vm.hostname = 'web01'
        config.vm.synced_folder '.', '/vagrant', disabled: true
        config.vm.network :forwarded_port, guest: 22, host: 2230, id: "ssh", auto_correct: false
    end
end
