# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site setting', 'verbose_name_plural': 'Site settings'},
        ),
    ]
