# Generated by Django 3.1.3 on 2020-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='language',
            field=models.CharField(choices=[('sv-SE', 'Swedish'), ('en-US', 'English'), ('de', 'German')], default='sv-SE', max_length=5),
        ),
    ]
